version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
